task:
  auto_cancellation: true

  env:
    matrix:
      PY_VER: "=3.6"
      PY_VER: " "

  matrix:
    - name: linux
      container:
        image: gcc:latest
      env:
        PATH: $HOME/conda/bin:$PATH
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
        - conda update -yn base conda
        - conda install -y python$PY_VER

    - name: windows
      windows_container:
        image: cirrusci/windowsservercore:2016
      env:
        PATH: $PATH;$USERPROFILE\anaconda\Scripts;$USERPROFILE\anaconda
      conda_script:
        - powershell -Command "curl https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile install.exe"
        - start /wait "" install.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=%USERPROFILE%\anaconda
        - conda update -yn base conda
        - conda install -y python%PY_VER%
        - pip install setuptools-scm

    - name: osx
      osx_instance:
        image: high-sierra-xcode-9.4.1
      env:
        PATH: $HOME/conda/bin:$PATH
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
        - conda update -yn base conda
        - conda install -y python$PY_VER

  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install --retries 3 -r requirements.txt
    - python setup.py develop

  check_script:
    - pip list
    - python -c "import napari; print(napari.__version__)"

  test_script:
    - pytest -v
